
language: java
sudo: false # faster builds

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN=:76c8c1e7-5878-4f9b-8c8a-56b7c33ea8a2